import 'dart:math' as math;

randomRetailers() {
  final List<String> retailers =[
    'Bunnings',
    'Adairs',
    'Adidas',
    'Adore Beauty',
    'Anaconda',
    'Appliances Online',
    'Autobarn',
    'Autograph',
    'BCF',
    'Best & Less',
    'Bicycles Online',
    'Big W',
    'Bing Lee',
    'Birdsnest',
    'Bonds',
    'Book Depository',
    'Booktopia',
    'Bras N Things',
    'Catch.com.au',
    'Centre Com',
    'Chemist Warehouse',
    'City Beach',
    'Coles',
    'Connor',
    'Cotton On',
    'Country Road',
    'Crazy Sales',
    'Crossroads',
    'Dan Murphys',
    'David Jones',
    'digiDirect',
    'Dusk',
    'Dymocks',
    'EB Games',
    'EziBuy',
    'First Choice Liquor',
    'Forever New',
    'General Pants',
    'Glassons',
    'Harvey Norman',
    'House',
    'HP',
    'Ikea',
    'JB Hi-Fi',
    'JD Sports',
    'Jeanswest',
    'Kathmandu',
    'Katies',
    'Kitchen Warehouse',
    'Kmart',
    'Koala',
    'Kogan',
    'Lenovo',
    'Lovehoney',
    'Mecca',
    'Michael Hill',
    'Microsoft',
    'Millers',
    'Mwave',
    'My Pet Warehouse',
    'Myer',
    'Naked Wines',
    'New Balance',
    'Nike',
    'Officeworks',
    'Ozsale',
    'PC Case Gear',
    'Pet Circle',
    'Petbarn',
    'Peter Alexander',
    'Peters of Kensington',
    'PETstock',
    'Platypus Shoes',
    'Prezzee',
    'Priceline',
    'Princess Polly',
    'Rebel',
    'Repco',
    'Sephora',
    'Shaver Shop',
    'Shein',
    'Skechers',
    'Spotlight',
    'Styletread',
    'Supercheap Auto',
    'SurfStitch',
    'Sydney Tools',
    'T2 Tea',
    'Target',
    "Ted's",
    'Temple & Webster',
    'Tent World',
    'The Good Guys',
    'The Iconic',
    'Under Armour',
    'Uniqlo',
    'Wild Earth',
    'Wild Secrets',
    'Witchery',
    'Woolworths',
    'JB-HI-FI, Collins St',
    'Bunnings, Boxhill',
    'Bunnings'
        'David Jones',
    '7-ELEVEN',
    'Apple',
    'H&M',
    'COLES',
    'Village Cinemas',
    'IKEA',
    'ABC Pty. Ltd.',
    'Happy Coffee',
    'Hudsons Coffee',
    'Starbucks',
  ];
  var rand = math.Random().nextInt(retailers.length);
  return retailers[rand];
}
