import 'dart:math' as math;

String randomSuburbs() {
  List<String> suburbs = [
  'Abbotsford',
  'Aberfeldie',
  'Aintree',
  'Airport West',
  'Albanvale',
  'Albert Park',
  'Albion',
  'Alphington',
  'Altona',
  'Altona Meadows',
  'Altona North',
  'Ardeer',
  'Armadale',
  'Arthurs Creek',
  'Arthurs Seat',
  'Ascot Vale',
  'Ashburton',
  'Ashwood',
  'Aspendale',
  'Aspendale Gardens',
  'Attwood',
  'Avondale Heights',
  'Avonsleigh',
  'Badger Creek',
  'Balaclava',
  'Balnarring',
  'Balnarring Beach',
  'Balwyn',
  'Balwyn North',
  'Bangholme',
  'Baxter',
  'Bayles',
  'Bayswater',
  'Bayswater North',
  'Beaconsfield',
  'Beaconsfield Upper',
  'Beaumaris',
  'Beenak',
  'Belgrave',
  'Belgrave Heights',
  'Belgrave South',
  'Bellfield',
  'Bend Of Islands',
  'Bentleigh',
  'Bentleigh East',
  'Berwick',
  'Beveridge',
  'Big Pats Creek',
  'Bittern',
  'Black Rock',
  'Blackburn',
  'Blackburn North',
  'Blackburn South',
  'Blairgowrie',
  'Blind Bight',
  'Bonbeach',
  'Boneo',
  'Bonnie Brook',
  'Boronia',
  'Botanic Ridge',
  'Box Hill',
  'Box Hill North',
  'Box Hill South',
  'Braeside',
  'Braybrook',
  'Briar Hill',
  'Brighton',
  'Brighton East',
  'Broadmeadows',
  'Brookfield',
  'Brooklyn',
  'Brunswick',
  'Brunswick East',
  'Brunswick West',
  'Bulla',
  'Bulleen',
  'Bundoora',
  'Bunyip',
  'Burnley',
  'Burnside',
  'Burnside Heights',
  'Burwood',
  'Burwood East',
  'Cairnlea',
  'Caldermeade',
  'Camberwell',
  'Campbellfield',
  'Cannons Creek',
  'Canterbury',
  'Cape Schanck',
  'Capel Sound',
  'Cardinia',
  'Carlton',
  'Carlton North',
  'Carnegie',
  'Caroline Springs',
  'Carrum',
  'Carrum Downs',
  'Catani',
  'Caulfield',
  'Caulfield East',
  'Caulfield North',
  'Caulfield South',
  'Chadstone',
  'Chelsea',
  'Chelsea Heights',
  'Cheltenham',
  'Cheltenham East',
  'Cheltenham North',
  'Chirnside Park',
  'Christmas Hills',
  'Chum Creek',
  'Clarinda',
  'Clayton',
  'Clayton South',
  'Clematis',
  'Clifton Hill',
  'Clyde',
  'Clyde North',
  'Cobblebank',
  'Coburg',
  'Coburg North',
  'Cockatoo',
  'Cocoroc',
  'Coldstream',
  'Collingwood',
  'Coolaroo',
  'Cora Lynn',
  'Cottles Bridge',
  'Craigieburn',
  'Cranbourne',
  'Cranbourne East',
  'Cranbourne North',
  'Cranbourne South',
  'Cranbourne West',
  'Cremorne',
  'Crib Point',
  'Croydon',
  'Croydon Hills',
  'Croydon North',
  'Croydon South',
  'Dallas',
  'Dalmore',
  'Dandenong',
  'Dandenong North',
  'Dandenong South',
  'Deepdene',
  'Deer Park',
  'Delahey',
  'Derrimut',
  'Devon Meadows',
  'Dewhurst',
  'Diamond Creek',
  'Diggers Rest',
  'Dingley',
  'Dingley Village',
  'Dixons Creek',
  'Docklands',
  'Don Valley',
  'Doncaster',
  'Doncaster East',
  'Donnybrook',
  'Donvale',
  'Doreen',
  'Doveton',
  'Dromana',
  'Eaglemont',
  'East Melbourne',
  'East Warburton',
  'Eden Park',
  'Edithvale',
  'Elsternwick',
  'Eltham',
  'Eltham North',
  'Elwood',
  'Emerald',
  'Endeavour Hills',
  'Epping',
  'Essendon',
  'Essendon North',
  'Essendon West',
  'Eumemmerring',
  'Exford',
  'Eynesbury',
  'Fairfield',
  'Fawkner',
  'Ferntree Gully',
  'Ferny Creek',
  'Fieldstone',
  'Fingal',
  'Fitzroy',
  'Fitzroy North',
  'Flemington',
  'Flinders',
  'Footscray',
  'Forest Hill',
  'Frankston',
  'Frankston North',
  'Frankston South',
  'Fraser Rise',
  'Gardenvale',
  'Garfield',
  'Garfield North',
  'Gembrook',
  'Gilderoy',
  'Gladstone Park',
  'Gladysdale',
  'Glan Devon',
  'Glen Huntly',
  'Glen Iris',
  'Glen Waverley',
  'Glenroy',
  'Gowanbrae',
  'Grangefields',
  'Greensborough',
  'Greenvale',
  'Gruyere',
  'Guys Hill',
  'Hadfield',
  'Hallam',
  'Hampton',
  'Hampton East',
  'Hampton Park',
  'Harkaway',
  'Harkness',
  'Hastings',
  'Hawksburn',
  'Hawthorn',
  'Hawthorn East',
  'Healesville',
  'Heath Hill',
  'Heatherton',
  'Heathmont',
  'Heidelberg',
  'Heidelberg Heights',
  'Heidelberg West',
  'Highett',
  'Hillside',
  'HMAS Cerberus',
  'Hoddles Creek',
  'Hoppers Crossing',
  'Hughesdale',
  'Humevale',
  'Huntingdale',
  'Hurstbridge',
  'Iona',
  'Ivanhoe',
  'Ivanhoe East',
  'Jacana',
  'Junction Village',
  'Kalkallo',
  'Kallista',
  'Kalorama',
  'Kangaroo Ground',
  'Kealba',
  'Keilor',
  'Keilor Downs',
  'Keilor East',
  'Keilor Lodge',
  'Keilor North',
  'Keilor Park',
  'Kensington',
  'Kew',
  'Kew East',
  'Keysborough',
  'Kilsyth',
  'Kilsyth South',
  'Kings Park',
  'Kingsbury',
  'Kingsville',
  'Knoxfield',
  'Koo Wee Rup',
  'Kooyong',
  'Kurunjang',
  'Lalor',
  'Lang Lang',
  'Langwarrin',
  'Langwarrin South',
  'Launching Place',
  'Laverton',
  'Laverton North',
  'Lilydale',
  'Little River',
  'Lower Plenty',
  'Lynbrook',
  'Lyndhurst',
  'Lysterfield',
  'Lysterfield South',
  'Macclesfield',
  'Macleod',
  'Maidstone',
  'Main Ridge',
  'Malvern',
  'Malvern East',
  'Mambourin',
  'Manor Lakes',
  'Maribyrnong',
  'Maryknoll',
  'McCrae',
  'McKinnon',
  'Meadow Heights',
  'Melbourne',
  'Melbourne (CBD)',
  'Melbourne Airport',
  'Melton',
  'Melton South',
  'Melton West',
  'Mentone',
  'Menzies Creek',
  'Mernda',
  'Merricks',
  'Merricks Beach',
  'Merricks North',
  'Mickleham',
  'Middle Park',
  'Mill Park',
  'Millgrove',
  'Mitcham',
  'Monbulk',
  'Monomeith',
  'Mont Albert',
  'Mont Albert North',
  'Montmorency',
  'Montrose',
  'Moonee Ponds',
  'Moorabbin',
  'Moorooduc',
  'Mooroolbark',
  'Mordialloc',
  'Mornington',
  'Mount Cottrell',
  'Mount Dandenong',
  'Mount Eliza',
  'Mount Evelyn',
  'Mount Martha',
  'Mount Waverley',
  'Mulgrave',
  'Murrumbeena',
  'Nangana',
  'Nar Nar Goon',
  'Nar Nar Goon North',
  'Narre Warren',
  'Narre Warren East',
  'Narre Warren North',
  'Narre Warren South',
  'Newport',
  'Niddrie',
  'Noble Park',
  'Noble Park North',
  'North Melbourne',
  'North Warrandyte',
  'Northcote',
  'Notting Hill',
  'Nunawading',
  'Nutfield',
  'Oak Park',
  'Oaklands Junction',
  'Oakleigh',
  'Oakleigh East',
  'Oakleigh South',
  'Officer',
  'Officer South',
  'Olinda',
  'Ormond',
  'Pakenham',
  'Pakenham South',
  'Pakenham Upper',
  'Panton Hill',
  'Park Orchards',
  'Parkdale',
  'Parkville',
  'Pascoe Vale',
  'Pascoe Vale South',
  'Patterson Lakes',
  'Pearcedale',
  'Plenty',
  'Plumpton',
  'Point Cook',
  'Point Leo',
  'Port Melbourne',
  'Portsea',
  'Powelltown',
  'Prahran',
  'Preston',
  'Princes Hill',
  'Quandong',
  'Ravenhall',
  'Red Hill',
  'Red Hill South',
  'Research',
  'Reservoir',
  'Richmond',
  'Ringwood',
  'Ringwood East',
  'Ringwood North',
  'Ripponlea',
  'Rockbank',
  'Rosanna',
  'Rosebud',
  'Rowville',
  'Roxburgh Park',
  'Rye',
  'Rythdale',
  'Safety Beach',
  'Saint Helena',
  'Sanctuary Lakes',
  'Sandhurst',
  'Sandringham',
  'Sassafras',
  'Scoresby',
  'Seabrook',
  'Seaford',
  'Seaholme',
  'Seddon',
  'Selby',
  'Seville',
  'Seville East',
  'Sherbrooke',
  'Shoreham',
  'Silvan',
  'Skye',
  'Smiths Gully',
  'Somers',
  'Somerton',
  'Somerville',
  'Sorrento',
  'South Kingsville',
  'South Melbourne',
  'South Morang',
  'South Yarra',
  'Southbank',
  'Spotswood',
  'Springvale',
  'Springvale South',
  'St Albans',
  'St Andrews',
  'St Andrews Beach',
  'St Kilda',
  'St Kilda East',
  'St Kilda West',
  'Steels Creek',
  'Strathmore',
  'Strathmore Heights',
  'Strathtulloh',
  'Sunbury',
  'Sunshine',
  'Sunshine North',
  'Sunshine West',
  'Surrey Hills',
  'Sydenham',
  'Tarneit',
  'Taylors Hill',
  'Taylors Lakes',
  'Tecoma',
  'Templestowe',
  'Templestowe Lower',
  'The Basin',
  'The Patch',
  'Thomastown',
  'Thornbury',
  'Thornhill Park',
  'Three Bridges',
  'Tonimbuk',
  'Toolern Vale',
  'Tooradin',
  'Toorak',
  'Tootgarook',
  'Tottenham',
  'Travancore',
  'Tremont',
  'Truganina',
  'Tuerong',
  'Tullamarine',
  'Tyabb',
  'Tynong',
  'Upper Ferntree Gully',
  'Upwey',
  'Vermont',
  'Vermont South',
  'Vervale',
  'Viewbank',
  'Wandin East',
  'Wandin North',
  'Wantirna',
  'Wantirna South',
  'Warburton',
  'Warneet',
  'Warrandyte',
  'Warrandyte South',
  'Warranwood',
  'Waterways',
  'Watsonia',
  'Watsonia North',
  'Wattle Glen',
  'Weir Views',
  'Werribee',
  'Werribee South',
  'Wesburn',
  'West Footscray',
  'West Melbourne',
  'Westmeadows',
  'Wheelers Hill',
  'Whittlesea',
  'Wildwood',
  'Willams Landing',
  'Williams Landing',
  'Williamstown',
  'Williamstown North',
  'Windsor',
  'Wollert',
  'Wonga Park',
  'Woodstock',
  'Woori Yallock',
  'Wyndham Vale',
  'Yallambie',
  'Yan Yean',
  'Yannathan',
  'Yarra Glen',
  'Yarra Junction',
  'Yarrambat',
  'Yarraville',
  'Yellingbo',
  'Yering'];

  var rand = math.Random().nextInt(suburbs.length);
  return suburbs[rand];
}
